# This is a basic workflow to help you get started with Actions

name: sync-submodules

on:
  workflow_dispatch:
  
jobs:
  sync:
    name: 'sync-submodules'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.CI_TOKEN }}
        submodules: true
    - name: Git Sumbodule Update
      run: |
        git pull --recurse-submodules
        git submodule update --init --recursive
        git submodule update --remote --recursive
    - name: Set Now Variable
      id: set-now-variable
      run: echo "NOW=`TZ=":Asia/Seoul" date +'%Y-%m-%d %H:%M:%S %z'`" >> $GITHUB_OUTPUT
    - name: Commit update
      run: |
        git config --global user.name 'Git bot'
        git config --global user.email 'bot@noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git commit -am "Auto updated submodule references on ${{ steps.set-now-variable.outputs.NOW }}" && git push || echo "No changes to commit"
